// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLU2L-nAO7OaDwYw5Urpy4JsVmRKTLN_c',
    appId: '1:295789011058:web:0376812191d6868b8b22eb',
    messagingSenderId: '295789011058',
    projectId: 'kokudo-a54c4',
    authDomain: 'kokudo-a54c4.firebaseapp.com',
    storageBucket: 'kokudo-a54c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXtJG-vpDkjFNF6-vJPvmJEiBpaN_6MdY',
    appId: '1:295789011058:android:5a5065eaf850c3bc8b22eb',
    messagingSenderId: '295789011058',
    projectId: 'kokudo-a54c4',
    storageBucket: 'kokudo-a54c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJX_3IeRdaVUTj5UFKN4rtKb5Z1AXq6E',
    appId: '1:295789011058:ios:0d89ea8f4e924d258b22eb',
    messagingSenderId: '295789011058',
    projectId: 'kokudo-a54c4',
    storageBucket: 'kokudo-a54c4.firebasestorage.app',
    iosBundleId: 'com.eggplantumrk.kokudo.kokudo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJX_3IeRdaVUTj5UFKN4rtKb5Z1AXq6E',
    appId: '1:295789011058:ios:0d89ea8f4e924d258b22eb',
    messagingSenderId: '295789011058',
    projectId: 'kokudo-a54c4',
    storageBucket: 'kokudo-a54c4.firebasestorage.app',
    iosBundleId: 'com.eggplantumrk.kokudo.kokudo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLU2L-nAO7OaDwYw5Urpy4JsVmRKTLN_c',
    appId: '1:295789011058:web:c2c423b242ac872c8b22eb',
    messagingSenderId: '295789011058',
    projectId: 'kokudo-a54c4',
    authDomain: 'kokudo-a54c4.firebaseapp.com',
    storageBucket: 'kokudo-a54c4.firebasestorage.app',
  );
}
